import type { Metadata } from "next";

import "./globals.css";
import Link from "next/link";
import { pageUrl } from "@/config/pageUrl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <nav>
          <ul className="flex flex-row gap-4">
            <li><Link href={pageUrl.home}>Home</Link></li>
            <li><Link href={pageUrl.login}>Login</Link></li>
            <li><Link href={pageUrl.register}>Register</Link></li>
          </ul>
      </nav>
      {children}
      </body>
    </html>
  );
}
